### ISSUE TITLE
cmake config files not in the right path

### ISSUE THREAD

**Issue by david-geiger** [10110111/CalcMySky#11]
Hi,

I see on Mageia Linux that the cmake config files are not in a standard path:

"/usr/lib(64)/ShowMySky-Qt6/cmake/ShowMySky-Qt5Config.cmake"

Shouldn't they be more in the following path?

"/usr/lib(64)/cmake/ShowMySky-Qt6/ShowMySky-Qt5Config.cmake"

   -install(EXPORT ShowMySky-Qt${QT_VERSION}Config NAMESPACE ShowMySky:: DESTINATION "${installConfDir}/ShowMySky-Qt${QT_VERSION}/cmake")
   +install(EXPORT ShowMySky-Qt${QT_VERSION}Config NAMESPACE ShowMySky:: DESTINATION "${installConfDir}/cmake/ShowMySky-Qt${QT_VERSION}")

Cheers,
David

**Comment by 10110111** [comment]
You appear to be right. I wonder though why CMake still does find it via `find_package()`.

**Comment by DarthGandalf** [comment]
Both of them are standard, and both of them work. The full list of directories it looks at is here: https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure

**Comment by DarthGandalf** [comment]
`cmake/<name>` is probably more popular though than `<name>/cmake`, looking at what's installed on my computer

**Comment by 10110111** [comment]
My Ubuntu 20.04 has the opposite ratio:
```
$ ls /usr/lib/*/cmake | wc -l
131
$ ls /usr/lib/cmake | wc -l
3
```

On a much older LFS with lots of legacy software installed the ratio is 97/76, which is closer to unity but still on the same side.

**Comment by DarthGandalf** [comment]
Try /usr/lib64 instead of lib

**Comment by DarthGandalf** [comment]
and also in share/

**Comment by 10110111** [comment]
Well on Ubuntu the arch-specific path is a bit different, but anyway, there's still fewer items there:
```
$ ls /usr/lib/x86_64-linux-gnu/cmake/ | wc -l
99
```

**Comment by 10110111** [comment]
> and also in share/

These ones don't contain anything interesting on Ubuntu.
