### ISSUE TITLE
/usr/bin/calcmysky lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK

### ISSUE THREAD

**Issue by carlosal1015** [10110111/CalcMySky#19]
Hi, I am not sure if some action is required, otherwise is safe to ignore.
```console
$ namcap calcmysky-0.3.2-1-x86_64.pkg.tar.zst 
calcmysky W: ELF file ('usr/bin/calcmysky') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
calcmysky W: ELF file ('usr/bin/showmysky') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
calcmysky W: ELF file ('usr/lib/libShowMySky-Qt6.so.15.0.0') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
calcmysky W: Dependency glibc detected and implicitly satisfied (libraries ['usr/lib/libc.so.6', 'usr/lib/libm.so.6'] needed in files ['usr/lib/libShowMySky-Qt6.so.15.0.0', 'usr/bin/showmysky', 'usr/bin/calcmysky'])
calcmysky W: Dependency gcc-libs detected and implicitly satisfied (libraries ['usr/lib/libstdc++.so.6', 'usr/lib/libgcc_s.so.1'] needed in files ['usr/lib/libShowMySky-Qt6.so.15.0.0', 'usr/bin/showmysky', 'usr/bin/calcmysky'])
calcmysky W: Dependency included, but may not be needed ('eigen')
calcmysky W: Dependency included, but may not be needed ('glm')
```

**Comment by 10110111** [comment]
> lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK

Shadow stack is a security feature that's not critical to the function. If your distribution requires it to be enabled, it's the packager's responsibility to enable this via `CMAKE_CXX_FLAGS` and `CMAKE_{EXE,SHARED}_LINKER_FLAGS`.

> detected and implicitly satisfied

Sounds OK.

> Dependency included, but may not be needed

Both Eigen and GLM are header-only libraries. If a binary package includes them, then it's a mistake of packaging. Do they get installed on `make install`? They shouldn't.
